version: '3.5'
services:
  backend:
    container_name: backend
    build: ./server/
    ports:
      - '8000:8000'
    volumes:
      - ./server/:/usr/src/app/
  frontend:
    container_name: frontend
    build: ./client/
    ports:
      - '80:80'
    volumes:
      - ./client/build/:/usr/share/nginx/html/